### ISSUE TITLE
[FEATURE] Responsive Website 2.0

### ISSUE THREAD

**Issue by vinzvinci** [web3community/app#1]
https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Untitled?node-id=0%3A1

## Tech Stack to use:
- HTML
- Tailwind CSS
- JavaScript
- Suggest JavaScript framework/libraries

## To Do
- Implement the design to code, try to use GitHub pages or you can suggest here

**Comment by vinzvinci** [comment]
This issue is big, so we can work as a team, we can collab on [Discord](https://discord.gg/BHa8Xn9Cgf) and take part in every feature.

**Comment by vinzvinci** [comment]
Please support our incoming contributors @mkubdev @Panquesito7 @shuklaritvik06 @KukretiShubham ^^

**Comment by krishguptadev** [comment]
I would like to work on this. But if this is eligible for hacktoberfest. I've already made my 4 prs, so let's wait if someone wants to make a pr. If not I would love to make one

**Comment by vinzvinci** [comment]
@krishguptadev speed 💯 

This is for hacktoberfest, yeah let's wait for the others first. I think 2-4 people can work with this issue.

**Comment by NarayanBavisetti** [comment]
I would like to contribute to this issue. We can work as a team. I have only made 1 PR.

**Comment by KukretiShubham** [comment]
Sure you can work on this. Also, you can join us [discord](https://discord.gg/pb4PA5kdRe) There we can collaborate better.

**Comment by NarayanBavisetti** [comment]
Can you assign me this task?

**Comment by chandresh1339** [comment]
I will be glad to work on the task. Please assign to me.

**Comment by vinzvinci** [comment]
> Sure you can work on this. Also, you can join us [discord](https://discord.gg/pb4PA5kdRe) There we can collaborate better.

Please join here @chandresh1339 for more guidance

**Comment by krishguptadev** [comment]
@vinzvinci Do you have any idea upon how more than 2 people are gonna work upon a issue that is just about 3-4 files?

**Comment by vinzvinci** [comment]
https://github.com/web3community/devprotocol.xyz/issues/1 pls continue here
